[package]
name = "advent_of_code2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
scanf = "1.2.1"
priority-queue = "1.3.0"
array2d = "0.3.0"
gcd = "2.2.0"
